#===========================================================================================
#------------------------------------#
#   FigureS11_Trends_Std_NS          |
#-------------------------------------#



# Program file to create a plot similar to the figure S11 in the supplementary material of the article (see section case study
# Figure S11. "Standardized net survival at 1 and 5 years as a function of the year of diagnosis in Cervical cancer." 
# 

# NOTE: 
# 	As we are not legally authorized to upload the actual real dataset of cervical cancer cases used in the case study,  
# 	we uploaded a simulated dataset. 
# 	Thus, the figure generated by this code will be different to the figure S11 in the supplementary material
#	

#===========================================================================================

# run 'ana_cervix.R' to load the cervix data and fit the model (object stored as tempmod)
exists("tempmod")
exists("cervix")


#===========================================================================================

	# load packages and functions

library(mgcv)
library(statmod)

# MyTP.gam: get the 'design' matrix for centered age 'agec', centered year of diagnosis 'adiagc', at the time=nodes value
MyTP.gam<-function(modele.gam,nodes,agec,adiagc)
{
	return(predict.gam(modele.gam,newdata=data.frame(intnum=nodes,agec=agec,ydiagc=adiagc),type="lpmatrix"))
}

# surv: Net survival computation
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
surv<-function(mat,param,weights)
{
	return(exp(-sum(exp(mat%*%as.numeric(param))*weights)))
}

# TxCum: cumulative hazard computation, similar to -log(surv(mat,param,weights))
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
TxCum<-function(mat,param,weights)
{
	return(sum(exp(mat%*%as.numeric(param))*weights))
}

# TauxX: derivative of the cumulative hazard; required for CI computation with Delta method
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
TauxX<-function(mat,param,weights,ii)
{
	sum(mat[,ii]*(exp(mat%*%as.numeric(param)))*weights)
}

# gauss.quad() returns the nodes and the weights for integration over interval [-1,1]
# 'Rescale' compute the nodes and the weights to integrate over interval [a,b]
# 	gl: object returned by function gauss.quad of package statmod
Rescale<-function(gl,a,b)
{
	gl$nodes <- gl$nodes*(b-a)/2+(a+b)/2
	gl$weights <- gl$weights*(b-a)/2
	return(gl)
}

#===========================================================================================

	# Standardized net survival estimation  (Multidimensional Penalysed Spline approach)

# See also 'CI_delta_Standardized_NS.R' for some comments about the code to produce Standardized NS estimates

# creation of the data.frame containting the ICSS weights for age-standardization
icss <-data.frame(
		typepop=rep(c("1","2","3","prostate"),each=5),
		ageclasse=c(rep(c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++["),3),
						c("[15;55[","[55;65[","[65;75[","[75;85[","[85;++[")),
		numclas=rep(rep(c(1:5),4)),
		wstd=c(
			c(0.07,0.12,0.23,0.29,0.29),
			c(0.28,0.17,0.21,0.20,0.14),
			c(0.60,0.10,0.10,0.10,0.10),
			c(0.19,0.23,0.29,0.23,0.06))
	)

# table.age: 1 row per age (rounded down) 
la<-floor(cervix$age)
lacl<-cut(la,breaks=c(0,45,55,65,75,200),labels=c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++["),right=FALSE,include.lowest=TRUE)
table.age<-data.frame(age=as.numeric(names(tapply(la,la,sum))),n=tapply(la,la,length),agecl=tapply(lacl,la,FUN=function(x)return(as.character(x[1]))))

# merge of table age and icss, and computation of weights for each age
table.age<-merge(table.age,icss[icss$typepop==2,c("ageclasse","wstd")],by.x="agecl",by.y="ageclasse")
ncl<-data.frame(agecl=names(table(lacl)),ncl=as.numeric(table(lacl)))
table.age<-merge(table.age,ncl,by="agecl")
table.age$wstd2<-table.age$wstd * (table.age$n/table.age$ncl)

# Trends in 1- and 5-year standardized net survival 
ltemps<-c(1,5)
ly<-seq(1989,2010.5,0.5)
la<-table.age$age

# table.yat: 1 row per time, age, and year of diagnosis
table.yat<-data.frame(temps=rep(ltemps,each=length(la)*length(ly)),adiag=rep(rep(ly,each=length(la)),length(ltemps)),age=rep(la,length(ltemps)*length(ly)))
table.yat<-merge(table.yat,table.age[,c("age","agecl","wstd2")],by="age")
table.yat$agec<-table.yat$age-70
table.yat$adiagc<-table.yat$adiag-2000
table.yat<-table.yat[order(table.yat$temps,table.yat$adiag,table.yat$age),]

GL<-gauss.quad(n=100,kind="legendre")

table.yat$surv<-NA
ly<-sort(unique(table.yat$adiag))
ltemps<-sort(unique(table.yat$temps))

# sstd: will store Standardized Net Survival estimation
# one row per time and year of diagnosis; --> data.frame with length(ltemps)*length(ly) rows
sstd<-data.frame(
	temps=rep(ltemps,each=length(ly)),adiag=rep(ly,length(ltemps)),
	sstd=rep(-1,length(ltemps)*length(ly)),se.logH=rep(-1,length(ltemps)*length(ly)))

# lcoef: estimated coefficients
lcoef<-tempmod$coefficients
# number of coefficients (6*5*4=120 here)
for(temps in ltemps)
{
	suppressWarnings(rm(gg,surv0,tempmat,temp2,tagec,tadiagc,PartialSurv,snstd,partialsn,partialLogT))
	gg <- Rescale(GL,0,temps)
	for(indy in 1:length(ly))
	{
		y<-ly[indy]
		# temptable : will contain net survival (multiplied by standard weights) by time 'temps', year 'y', and age 
		# 1 row per age (for a given time 'temps' and year 'y')
		temptable<-table.yat[table.yat$adiag==y & table.yat$temps==temps,]
		
		for(x in 1:(dim(temptable)[1]))
		{
			tagec<-temptable$agec[x]
			tadiagc<-temptable$adiagc[x]
			# tempmat: design matrix for centered age 'tagec', year 'tadiagc', and for each time=node value
			tempmat<-MyTP.gam(modele.gam=tempmod,nodes=gg$nodes,agec=tagec,adiagc=tadiagc)
			surv0<-surv(tempmat,lcoef,gg$weights)
			temptable$surv[x]<-surv0*temptable$wstd2[x]
		}
		# snstd: standardized net survival at time 'temps' and year 'y'
		snstd<-sum(temptable$surv)
		sstd$sstd[sstd$temps==temps & sstd$adiag==y]<-snstd
	}
}

#===========================================================================================


	# Non-parametric estimation of standardized net survival using the Pohar-Perme method

# In this section, computation of Std. NS estimates is performed using the non-parametric Pohar-Perme method
# These estimates (with CI) will be added to the figure as gray segments
# Use of the function rs.surv() of package relsurv to estimate net survival by age-class
# See Perme 2012. Biometrics
# See also the help of rs.surv() and package relsurv

library(relsurv)

# The 'expected' mortality hazard of the general population must be stored as a 'ratetable' object
# This 'ratetable' object is loaded here
# my.rep<-"S:/etude35/3596_survie_1989_2013/communic/paper_tensor/soumission_SMMR_2018_03_23/review_2018_04_18/github/"
load(paste(my.rep,"data/ExpectedHazard_ratetable.RData",sep=""))
# print(class(exp.hazard.rt)) 
# print(attributes(exp.hazard.rt))


# Non-parametrics Std. NS estimates at time t=1 and 5 years, and by period of diagnosis (4 periods: [1989,1994), [1994,1999), [1999,2005), [2005,2011))
ltemps<-c(1,5)
lperdeb<-c(1989,1994,1999,2005)
lperfin<-c(1994,1999,2005,2011)
# NS will first be estimated by age-class, the standardize NS will then be the weighted sum of these age-class estimates (using ICSS weights)
lagecl<-c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++[")
lagedeb<-c(0,45,55,65,75)
lagefin<-c(45,55,65,75,200)

sn.PP.agecl<-data.frame(
	temps=rep(ltemps,each=length(lagecl)*length(lperdeb)),
	anneedeb=rep(rep(lperdeb,each=length(lagecl)),length(ltemps)),
	anneefin=rep(rep(lperfin,each=length(lagecl)),length(ltemps)),
	agecl=rep(lagecl,length(ltemps)*length(lperdeb)))

sn.PP.agecl<-merge(sn.PP.agecl,icss[icss$typepop==2,c("ageclasse","wstd")],by.x="agecl",by.y="ageclasse")
sn.PP.agecl$sn<-NA
sn.PP.agecl$var.sn<-NA
sn.PP.agecl<-sn.PP.agecl[order(sn.PP.agecl$temps,sn.PP.agecl$anneedeb,sn.PP.agecl$agecl),]


# expected hazard in the ratetable is expressed in deaths per person-DAY; age and length of follow-up are thus also converted to days
cervix$time5y.day<-cervix$time5 * 365.25
cervix$age.day<-cervix$age * 365.25
# the cutoff points for dimension 'year' in exp.hazard.rt correspond to the difference in DAYS between 1960-01-01 and January the 1st of the current year of death
# diag.1960 is a transformation of the date of diagnosis, so that it matchs the cutoff points in exp.hazard.rt 
cervix$diag.1960<-as.numeric(difftime(as.Date(paste(cervix$ydiag,"-01-01",sep=""),format="%Y-%m-%d"),"1960-01-01"))

cervix$AGECLASSE<-as.character(NA)
cervix$AGECLASSE[cervix$age>=15]<-"[15;45["
cervix$AGECLASSE[cervix$age>=45]<-"[45;55["
cervix$AGECLASSE[cervix$age>=55]<-"[55;65["
cervix$AGECLASSE[cervix$age>=65]<-"[65;75["
cervix$AGECLASSE[cervix$age>=75]<-"[75;++["

# Pohar-Perme estimates by age-class
for(indan in 1:length(lperdeb))
{
	andeb<-lperdeb[indan]
	anfin<-lperfin[indan]
	for(indage in 1:length(lagecl))
	{
		agedeb<-lagedeb[indage]
		agefin<-lagefin[indage]
		tempdon<-cervix[cervix$ydiag>=andeb & cervix$ydiag<anfin & cervix$AGECLASSE==lagecl[indage],]
		surv.pp<-summary(rs.surv(Surv(time5y.day, status5)~1+ratetable(age=age.day, sex=sex, year=diag.1960),
			data=tempdon, ratetable=exp.hazard.rt,type="fleming-harrington",conf.type="log-log"),time=ltemps*365.25)
		
		for(indtemps in 1:length(ltemps))
		{
			sn.PP.agecl$sn[sn.PP.agecl$anneedeb==andeb & sn.PP.agecl$agecl==lagecl[indage] & sn.PP.agecl$temps==ltemps[indtemps]]<-surv.pp$surv[indtemps]
			sn.PP.agecl$var.sn[sn.PP.agecl$anneedeb==andeb & sn.PP.agecl$agecl==lagecl[indage] & sn.PP.agecl$temps==ltemps[indtemps]]<-(surv.pp$std.err[indtemps])^2
		}
	}
}
# CI will be computed for standardized NS estimates using delta method
# these CIs will also be added to the figure as vertical segments
sn.PP.agecl$var.logsn<- sn.PP.agecl$var.sn/((sn.PP.agecl$sn)^2)
sn.PP.agecl$sn.inf<-100*exp(log(sn.PP.agecl$sn)+qnorm(0.025)*sqrt(sn.PP.agecl$var.logsn))
sn.PP.agecl$sn.sup<-100*exp(log(sn.PP.agecl$sn)-qnorm(0.025)*sqrt(sn.PP.agecl$var.logsn))
sn.PP.agecl$surv<-100*sn.PP.agecl$sn
sn.PP.agecl$IC<-paste(round(sn.PP.agecl$surv,1)," [",round(sn.PP.agecl$sn.inf,1),",",round(sn.PP.agecl$sn.sup,1),"]",sep="")


# Age-standardization
sn.PP.std<-data.frame(temps=rep(ltemps,each=length(lperdeb)),anneedeb=rep(lperdeb,length(ltemps)),anneefin=rep(lperfin,length(ltemps)))
sn.PP.std$sn<-NA
sn.PP.std$sn.inf<-NA
sn.PP.std$sn.sup<-NA
for(indan in 1:length(lperdeb))
{
	andeb<-lperdeb[indan]
	anfin<-lperfin[indan]
	for(indtemps in 1:length(ltemps))
	{
		suppressWarnings(rm(tempsn))
		tempsn<-sn.PP.agecl[sn.PP.agecl$temps==ltemps[indtemps] & sn.PP.agecl$anneedeb==andeb,]
		sn.PP.std$sn[sn.PP.std$temps==ltemps[indtemps] & sn.PP.std$anneedeb==andeb]<-sum(tempsn$sn*tempsn$wstd)
		sn.PP.std$var.sn[sn.PP.std$temps==ltemps[indtemps] & sn.PP.std$anneedeb==andeb]<-sum((tempsn$wstd)^2 * tempsn$var.sn)
	}
}

sn.PP.std$se.logsn<- sqrt(sn.PP.std$var.sn/((sn.PP.std$sn)^2))
sn.PP.std$sn.inf<-100*exp(log(sn.PP.std$sn)+qnorm(0.025)*sn.PP.std$se.logsn)
sn.PP.std$sn.sup<-100*exp(log(sn.PP.std$sn)-qnorm(0.025)*sn.PP.std$se.logsn)
sn.PP.std$surv<-100*sn.PP.std$sn
sn.PP.std$IC<-paste(round(sn.PP.std$surv,1)," [",round(sn.PP.std$sn.inf,1),",",round(sn.PP.std$sn.sup,1),"]",sep="")

# print(sn.PP.std)

#===========================================================================================

	# Creation of the Figure S11 
	# Standardized net survival at 1 and 5 years as a function of the year of diagnosis in Cervical cancer.

my.res<-paste(my.rep,"res/",sep="")
nomgraphe<-"FigureS11_Trends_Std_NS.eps"

# several graphical parameters are set here
lymax=NULL
width=18
height=7
marbas=3
margauche=3
pos.leg="topright"
min.yaxis=0.1
max.yaxis=2
hor.leg=FALSE
# set plotPP to FALSE if you do not want the Pohar-Perme estimates in your plot
plotPP=TRUE

postscript(file=paste(my.res,nomgraphe,sep=""), horizontal=F, width=width/2.54, height=height/2.54,paper="special")
par(mfrow=c(1,2),mar=c(marbas,margauche,0,0),mgp=c(1.5,0.5,0),oma=c(0,0,0.5,0.5))
for(temps in ltemps)
{
	# temps<-1
	if(!plotPP)
		ylim<-c(floor(min(100*c(sstd$sstd[sstd$temps==temps]),na.rm=T)/10)*10,ceiling(max(100*c(sstd$sstd[sstd$temps==temps]),na.rm=T)/10)*10)
	if(plotPP)
	{
		temppp<-sn.PP.std[sn.PP.std$temps==temps,]
		ylim<-c(floor(min(100*c(sstd$sstd[sstd$temps==temps],temppp$sn),na.rm=T)/10)*10,
				ceiling(max(100*c(sstd$sstd[sstd$temps==temps],temppp$sn),na.rm=T)/10)*10)
	}
	if(ylim[1]<10)
		ylim[1]<-0
	if(ylim[2]>90)
		ylim[2]<-100
	if(ylim[2]<=10)
		ylim[2]<-15
	if(ylim[1]>=90)
		ylim[1]<-85
	if(ylim[2]-ylim[1]<=15)
	{
		ylim[1]<-max(ylim[1]-5,0)
		ylim[2]<-min(ylim[2]+5,100)
	}
	plot(sstd$adiag[sstd$temps==temps],100*sstd$sstd[sstd$temps==temps],xlim=c(1989,2011),ylim=ylim,type="n",xlab="Year of diagnosis",ylab="Net survival",cex.lab=0.9,cex.axis=0.8)
	
	if(plotPP)
	{
		segments(x0=temppp$anneedeb,y0=temppp$surv,x1=temppp$anneefin,y1=temppp$surv,col="gray50",lty=1,lwd=1.5)
		segments(x0=(temppp$anneedeb+temppp$anneefin)/2,y0=temppp$sn.inf,x1=(temppp$anneedeb+temppp$anneefin)/2,y1=temppp$sn.sup,col="gray50",lty=1,lwd=1.2)
	}
	lines(sstd$adiag[sstd$temps==temps],100*sstd$sstd[sstd$temps==temps],lty="solid",col="red",lwd=1.7)
	
	if(temps==ltemps[1])
	{
		if(plotPP)
			legend("bottomleft",legend=c("MPS","PP Est."),lty=c("solid","solid"),col=c("red","gray50"),pch=c(NA,3),cex=0.8,horiz=hor.leg,lwd=c(1.7,1.3))
	}
	mtext(paste("Time t=",temps," year",ifelse(temps>1,"s",""),sep=""),side=3,outer=FALSE,line=-1.5,cex=0.85)
}
dev.off()


