#-------------------------------------#
#   FigureS12_Trends_NS_by_Age.R      |
#-------------------------------------#



# Program file to create a plot similar to the figure S12 in the supplementary material of the article (see section case study
# Figure S12. "Net survival (NS) at 1 and 5 years as a function of the year of diagnosis in Cervical cancer, by age." 
# 

# NOTE: 
# 	As we are not legally authorized to upload the actual real dataset of cervical cancer cases used in the case study,  
# 	we uploaded a simulated dataset. 
# 	Thus, the figure generated by this code will be different to the figure S12 in the supplementary material
#	

#===========================================================================================

# run 'ana_cervix.R' to load the cervix data and fit the model (object stored as tempmod)
exists("tempmod")
exists("cervix")

#===========================================================================================

	# load packages and functions

library(mgcv)
library(statmod)

# MyTP.gam: get the 'design' matrix for centered age 'agec', centered year of diagnosis 'adiagc', at the time=nodes value
MyTP.gam<-function(modele.gam,nodes,agec,adiagc)
{
	return(predict.gam(modele.gam,newdata=data.frame(intnum=nodes,agec=agec,ydiagc=adiagc),type="lpmatrix"))
}

# surv: Net survival computation
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
surv<-function(mat,param,weights)
{
	return(exp(-sum(exp(mat%*%as.numeric(param))*weights)))
}

# TxCum: cumulative hazard computation, similar to -log(surv(mat,param,weights))
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
TxCum<-function(mat,param,weights)
{
	return(sum(exp(mat%*%as.numeric(param))*weights))
}

# TauxX: derivative of the cumulative hazard; required for CI computation with Delta method
# 	mat: 'design' matrix, as returned by function 'MyTP.gam'
#	param: estimated coefficients 
# 	weights: weights of Gauss-Legendre quadrature
TauxX<-function(mat,param,weights,ii)
{
	sum(mat[,ii]*(exp(mat%*%as.numeric(param)))*weights)
}

# gauss.quad() returns the nodes and the weights for integration over interval [-1,1]
# 'Rescale' compute the nodes and the weights to integrate over interval [a,b]
# 	gl: object returned by function gauss.quad of package statmod
Rescale<-function(gl,a,b)
{
	gl$nodes <- gl$nodes*(b-a)/2+(a+b)/2
	gl$weights <- gl$weights*(b-a)/2
	return(gl)
}

#===========================================================================================


	# Net survival estimates at t=1 and 5 years and at 5 ages (Multidimensional Penalysed Spline approach)

# See also 'CI_delta_NS.R' for some comments about the code to produce NS estimates

la<-floor(cervix$age)
lacl<-cut(la,breaks=c(0,45,55,65,75,200),labels=c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++["),right=FALSE,include.lowest=TRUE)
table.age<-data.frame(age=as.numeric(names(tapply(la,la,sum))),n=tapply(la,la,length),agecl=tapply(lacl,la,FUN=function(x)return(as.character(x[1]))))

ltemps<-c(1,5)
ly<-seq(1989,2010.5,0.5)

cervix$AGECLASSE<-as.character(NA)
cervix$AGECLASSE[cervix$age>=15]<-"[15;45["
cervix$AGECLASSE[cervix$age>=45]<-"[45;55["
cervix$AGECLASSE[cervix$age>=55]<-"[55;65["
cervix$AGECLASSE[cervix$age>=65]<-"[65;75["
cervix$AGECLASSE[cervix$age>=75]<-"[75;++["
# get the median of age WITHIN each age-class
print(tapply(cervix$age,cervix$AGECLASSE,summary))
lmed.clage<-tapply(cervix$age,factor(cervix$AGECLASSE),median)

lagecl<-levels(factor(cervix$AGECLASSE))
lage<-lmed.clage[lagecl]

table.yat<-data.frame(	temps=rep(ltemps,each=length(lage)*length(ly)),
						adiag=rep(rep(ly,each=length(lage)),length(ltemps)),
						age=rep(lage,length(ltemps)*length(ly)))
table.yat$agec<-table.yat$age-70
table.yat$adiagc<-table.yat$adiag-2000
table.yat<-table.yat[order(table.yat$temps,table.yat$adiag,table.yat$age),]

GL<-gauss.quad(n=100,kind="legendre")

table.yat$surv<-NA
ly<-sort(unique(table.yat$adiag))
ltemps<-sort(unique(table.yat$temps))

# lcoef: estimated coefficients
lcoef<-tempmod$coefficients
# number of coefficients (6*5*4=120 here)
for(temps in ltemps)
{
	suppressWarnings(rm(gg,surv0,tempmat,temp2,tagec,tadiagc,PartialSurv,snstd,partialsn,partialLogT))
	gg <- Rescale(GL,0,temps)
	for(indy in 1:length(ly))
	{
		y<-ly[indy]
		# temptable : will contain net survival (multiplied by standard weights) by time 'temps', year 'y', and age 
		# 1 row per age (for a given time 'temps' and year 'y')
		temptable<-table.yat[table.yat$adiag==y & table.yat$temps==temps,]
		
		for(x in 1:(dim(temptable)[1]))
		{
			tagec<-temptable$agec[x]
			tadiagc<-temptable$adiagc[x]
			# tempmat: design matrix for centered age 'tagec', year 'tadiagc', and for each time=node value
			tempmat<-MyTP.gam(modele.gam=tempmod,nodes=gg$nodes,agec=tagec,adiagc=tadiagc)
			surv0<-surv(tempmat,lcoef,gg$weights)
			temptable$surv[x]<-surv0
		}
		table.yat[table.yat$adiag==y & table.yat$temps==temps,"surv"]<-temptable$surv
	}
}

#===========================================================================================


	# Non-parametric estimation of net survival using the Pohar-Perme method

# In this section, computation of NS estimates is performed using the non-parametric Pohar-Perme method
# These estimates (with CI) will be added to the figure as gray segments
# Use of the function rs.surv() of package relsurv to estimate net survival by age-class
# See Perme 2012. Biometrics
# See also the help of rs.surv() and package relsurv

library(relsurv)

# The 'expected' mortality hazard of the general population must be stored as a 'ratetable' object
# This 'ratetable' object is loaded here
# my.rep<-"S:/etude35/3596_survie_1989_2013/communic/paper_tensor/soumission_SMMR_2018_03_23/review_2018_04_18/github/"
load(paste(my.rep,"data/ExpectedHazard_ratetable.RData",sep=""))
# print(class(exp.hazard.rt)) 
# print(attributes(exp.hazard.rt))


# Non-parametrics Std. NS estimates at time t=1 and 5 years,
# by period of diagnosis (4 periods: [1989,1994), [1994,1999), [1999,2005), [2005,2011)),
# and by age-class (5 age-classes: c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++["))
ltemps<-c(1,5)
lperdeb<-c(1989,1994,1999,2005)
lperfin<-c(1994,1999,2005,2011)
# NS will first be estimated by age-class, the standardize NS will then be the weighted sum of these age-class estimates (using ICSS weights)
lagecl<-c("[15;45[","[45;55[","[55;65[","[65;75[","[75;++[")
lagedeb<-c(0,45,55,65,75)
lagefin<-c(45,55,65,75,200)

sn.PP.agecl<-data.frame(
	temps=rep(ltemps,each=length(lagecl)*length(lperdeb)),
	anneedeb=rep(rep(lperdeb,each=length(lagecl)),length(ltemps)),
	anneefin=rep(rep(lperfin,each=length(lagecl)),length(ltemps)),
	agecl=rep(lagecl,length(ltemps)*length(lperdeb)))

sn.PP.agecl<-merge(sn.PP.agecl,icss[icss$typepop==2,c("ageclasse","wstd")],by.x="agecl",by.y="ageclasse")
sn.PP.agecl$sn<-NA
sn.PP.agecl$var.sn<-NA
sn.PP.agecl<-sn.PP.agecl[order(sn.PP.agecl$temps,sn.PP.agecl$anneedeb,sn.PP.agecl$agecl),]


# expected hazard in the ratetable is expressed in deaths per person-DAY; age and length of follow-up are thus also converted to days
cervix$time5y.day<-cervix$time5 * 365.25
cervix$age.day<-cervix$age * 365.25
# the cutoff points for dimension 'year' in exp.hazard.rt correspond to the difference in DAYS between 1960-01-01 and January the 1st of the current year of death
# diag.1960 is a transformation of the date of diagnosis, so that it matchs the cutoff points in exp.hazard.rt 
cervix$diag.1960<-as.numeric(difftime(as.Date(paste(cervix$ydiag,"-01-01",sep=""),format="%Y-%m-%d"),"1960-01-01"))

# Pohar-Perme estimates by age-class
for(indan in 1:length(lperdeb))
{
	andeb<-lperdeb[indan]
	anfin<-lperfin[indan]
	for(indage in 1:length(lagecl))
	{
		agedeb<-lagedeb[indage]
		agefin<-lagefin[indage]
		tempdon<-cervix[cervix$ydiag>=andeb & cervix$ydiag<anfin & cervix$AGECLASSE==lagecl[indage],]
		surv.pp<-summary(rs.surv(Surv(time5y.day, status5)~1+ratetable(age=age.day, sex=sex, year=diag.1960),
			data=tempdon, ratetable=exp.hazard.rt,type="fleming-harrington",conf.type="log-log"),time=ltemps*365.25)
		
		for(indtemps in 1:length(ltemps))
		{
			sn.PP.agecl$sn[sn.PP.agecl$anneedeb==andeb & sn.PP.agecl$agecl==lagecl[indage] & sn.PP.agecl$temps==ltemps[indtemps]]<-surv.pp$surv[indtemps]
			sn.PP.agecl$var.sn[sn.PP.agecl$anneedeb==andeb & sn.PP.agecl$agecl==lagecl[indage] & sn.PP.agecl$temps==ltemps[indtemps]]<-(surv.pp$std.err[indtemps])^2
		}
	}
}
# CIs will also be added to the figure as gray vertical segments
sn.PP.agecl$var.logsn<- sn.PP.agecl$var.sn/((sn.PP.agecl$sn)^2)
sn.PP.agecl$sn.inf<-100*exp(log(sn.PP.agecl$sn)+qnorm(0.025)*sqrt(sn.PP.agecl$var.logsn))
sn.PP.agecl$sn.sup<-100*exp(log(sn.PP.agecl$sn)-qnorm(0.025)*sqrt(sn.PP.agecl$var.logsn))
sn.PP.agecl$surv<-100*sn.PP.agecl$sn
sn.PP.agecl$IC<-paste(round(sn.PP.agecl$surv,0)," [",round(sn.PP.agecl$sn.inf,0),",",round(sn.PP.agecl$sn.sup,0),"]",sep="")

print(sn.PP.agecl)

#===========================================================================================

	# Creation of the Figure S12
	# Net survival (NS) at 1 and 5 years as a function of the year of diagnosis in Cervical cancer, by age.

my.res<-paste(my.rep,"res/",sep="")
nomgraphe<-"FigureS12_Trends_NS_by_Age.eps"

# several graphical parameters are set here
lymax=NULL
width=17
height=25.5
marbas=3
margauche=3
marhaut=0
pos.leg="topright"
min.yaxis=0.1
max.yaxis=2
hor.leg=FALSE
# set plotPP to FALSE if you do not want the Pohar-Perme estimates in your plot
plotPP=TRUE


postscript(file=paste(my.res,nomgraphe,sep=""), horizontal=F, width=width/2.54, height=height/2.54,paper="special")

	nf<-layout(matrix(
			c(	0,11,12,
				13,1,2,
				14,3,4,
				15,5,6,
				16,7,8,
				17,9,10),
			nrow=6,ncol=3,byrow=TRUE),
			respect=FALSE,
			widths=c(0.1,1.5,1.5),
			heights=c(0.15,rep(1,5)))
par(mar=c(marbas,margauche,marhaut,0),mgp=c(1.5,0.5,0),oma=c(0,0,0,0.5))

for(indage in 1:length(lage))
{
	for(temps in ltemps)
	{
		if(plotPP)
		{
			temppp<-sn.PP.agecl[sn.PP.agecl$temps==temps & sn.PP.agecl$agecl==lagecl[indage],]
		}
		if(temps==1)
		{
			ylim<-c(60,100)
		}
		if(temps==5)
		{
			if(indage %in% 1:2)
				ylim<-c(60,100)
			if(indage %in% c(3,4))
				ylim<-c(40,80)
			if(indage %in% c(5))
				ylim<-c(20,60)
		}
		plot(table.yat$adiag[table.yat$temps==temps & round(table.yat$age,1)==round(lage[indage],1)],100*table.yat$surv[table.yat$temps==temps & round(table.yat$age,1)==round(lage[indage],1)],xlim=c(1989,2011),ylim=ylim,type="n",xlab="Year of diagnosis",ylab="Net survival",cex.lab=1,cex.axis=0.9)
	
		if(plotPP)
		{
			segments(x0=temppp$anneedeb,y0=temppp$surv,x1=temppp$anneefin,y1=temppp$surv,col="gray50",lty=1,lwd=1.5)
			segments(x0=(temppp$anneedeb+temppp$anneefin)/2,y0=temppp$sn.inf,x1=(temppp$anneedeb+temppp$anneefin)/2,y1=temppp$sn.sup,col="gray50",lty=1,lwd=1.2)
		}
		lines(table.yat$adiag[table.yat$temps==temps & round(table.yat$age,1)==round(lage[indage],1)],100*table.yat$surv[table.yat$temps==temps & round(table.yat$age,1)==round(lage[indage],1)],lty="solid",col="red",lwd=1.7)
	
		if(indage==3)
		{
			if(plotPP)
				legend("bottom",legend=c("MPS","PP Est."),lty=c("solid","solid"),col=c("red","gray50"),pch=c(NA,3),cex=1,horiz=hor.leg,lwd=c(1.7,1.3))
		}
	}
}

		# # Column labels
		# #--------------

par(mar=c(0,margauche,0,0),mgp=c(2,0.5,0))
for(temps in ltemps)
{
	plot(0:1,0:1,type="n",axes=FALSE,xlab="",ylab="")
	text(0.5,0.5,paste("Time t=",temps," year",ifelse(temps>1,"s",""),sep=""),cex=1.5)
}

		# intitulé ligne
lagecl.pr<-c("15-44","45-54","55-64","65-74","\u2265 75")
par(mar=c(marbas,0,marhaut,0),mgp=c(0,0,0))
for(indage in 1:length(lage))
{
		plot(0:1,0:1,type="n",axes=FALSE,xlab="",ylab="")
	if(indage!=5)
		text(0.5,0.5,paste("Age ",round(lage[indage],0)," (",lagecl.pr[indage],")",sep=""),srt=90,cex=1.4)
	if(indage==5)
	
		text(0.5,0.5,expression("Age 81 (" >="75)"),srt=90,cex=1.4)
}

dev.off()


