#-------------------------------------#
#   FigureS13_ExcessHazard.R      |
#-------------------------------------#


# Program file to create a plot similar to the figure S12 in the supplementary material of the article (see section case study
# Figure S13. "Excess mortality hazard as a function of time since diagnosis in Cervical cancer, at 5 ages." 
# 

# NOTE: 
# 	As we are not legally authorized to upload the actual real dataset of cervical cancer cases used in the case study,  
# 	we uploaded a simulated dataset. 
# 	Thus, the figure generated by this code will be different to the figure S13 in the supplementary material
#	

#===========================================================================================

# run 'ana_cervix.R' to load the cervix data and fit the model (object stored as tempmod)
exists("tempmod")
exists("cervix")


#===========================================================================================

	# load packages and functions

library(splines)
library(mgcv)

# getTx.gam: small functions to estimate excess hazard at time since diagnosis t='temps', year y='an' and age a='age' 
# 	modele.gam: gamObject corresponding to the fit of the MPS approach
# ageref: reference age to compute agec 
getTx.gam<-function(modele.gam,an,age,temps,ageref=70)
{

	datpred<-data.frame(intnum=temps,ydiagc=an-2000,agec=age-ageref,an=an,age=age)
	datpred$tx<-exp(predict.gam(modele.gam,newdata=datpred,type="lpmatrix")%*%coef(modele.gam))
	return(datpred)
}

#===========================================================================================

	# Computation of excess hazard 


ltemps<-seq(0,5,by=0.05)
# 3 curves will be plotted in each panel, one for year of diagnosis 1990, one for 2000, and one for 2010
lan<-seq(1990,2010,by=10)

cervix$AGECLASSE<-as.character(NA)
cervix$AGECLASSE[cervix$age>=15]<-"[15;45["
cervix$AGECLASSE[cervix$age>=45]<-"[45;55["
cervix$AGECLASSE[cervix$age>=55]<-"[55;65["
cervix$AGECLASSE[cervix$age>=65]<-"[65;75["
cervix$AGECLASSE[cervix$age>=75]<-"[75;++["
# get the median of age WITHIN each age-class
print(tapply(cervix$age,cervix$AGECLASSE,summary))
lmed.clage<-tapply(cervix$age,factor(cervix$AGECLASSE),median)
lagecl<-levels(factor(cervix$AGECLASSE))
lage<-lmed.clage[lagecl]

print(lage)
#----------------

suppressWarnings(rm(preddat))
preddat.te<-getTx.gam(modele.gam=tempmod,
			an=rep(lan,each=length(lage)*length(ltemps)),
			age=rep(rep(lage,each=length(ltemps)),length(lan)),
			temps=rep(ltemps,length(lan)*length(lage)))

#===========================================================================================

	# Creation of the Figure S13
	# Excess mortality hazard as a function of time since diagnosis in Cervical cancer, at 5 ages.

my.res<-paste(my.rep,"res/",sep="")
nomgraphe<-"FigureS13_ExcessHazard.eps"

# several graphical parameters are set here
lymax=NULL
width=21
height=11.5
marbas=3
margauche=3
pos.leg="topright"
min.yaxis=0.1
max.yaxis=2
hor.leg=FALSE
			
	
#--------------------------------------------------------

	# graphe tx (comme fig. 1 article) : MPS Vs. PH
	#-----------------------------------------------


my.res<-paste(my.rep,"res/",sep="")
nomgraphe<-"FigureS13_ExcessHazard.eps"

postscript(file=paste(my.res,nomgraphe,sep=""), horizontal=F, width=width/2.54, height=height/2.54,paper="special")

	nf<-layout(matrix(
			c(	1,1,2,2,3,3,
				0,4,4,5,5,0),
			nrow=2,ncol=6,byrow=TRUE),
			respect=FALSE,
			widths=c(rep(1/6,6)),
			heights=c(rep(1,2))
		)
		
par(mar=c(marbas,margauche,0,0),mgp=c(1.5,0.5,0),oma=c(0,0,0.5,0.5))
for(age in lage)
{
	ylim<-c(0,ceiling(max(c(preddat.te$tx[round(preddat.te$age,1)==round(age,1) & preddat.te$intnum>0])*20))/20)
	if(ylim[2]<min.yaxis)
		ylim[2]<-min.yaxis
	if(ylim[2]>max.yaxis)
		ylim[2]<-max.yaxis
	ymax<-ylim[2]			
	by.y<-0.05
	by.y[ymax>0.25]<-0.1
	by.y[ymax>0.5]<-0.2
	by.y[ymax>1.5]<-0.5
	plot(preddat.te$intnum,preddat.te$tx,type="n",ylim=ylim, xlab="Time since diagnosis", ylab="Excess hazard")
	abline(h=seq(0,ymax,by=by.y),col="lightgray",lty=8,lwd=0.8)
	abline(h=0,col="lightgray",lty=1,lwd=0.8)
	
	lcol<-1:3
	lpch=c(NA,8,17)
	for(indan in 1:length(lan))
	{
		an<-lan[indan]
		lines(preddat.te$intnum[preddat.te$an==an & round(preddat.te$age,1)==round(age,1)],preddat.te$tx[preddat.te$an==an & round(preddat.te$age,1)==round(age,1)],col=lcol[indan],lwd=1.5,lty=1)
	}
	if(round(age,1)==round(lage[1],1))
	{
		legend("topright",legend=lan,lty=rep(1,3),col=lcol,cex=0.9,horiz=hor.leg)
	}
	mtext(paste("Age ",round(age,0),sep=""),side=3,outer=FALSE,line=-1.5,cex=0.85)
}

dev.off()



